# fly.toml app configuration file generated for sherlock-drf-api on 2023-05-31T22:18:08+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
5538 1348

app = "sherlock-drf-api"
primary_region = "sea"
console_command = "/code/manage.py shell"
kill_signal="SIGINT"

[env]
  PORT = "8000"
  DJANGO_SETTINGS_MODULE = "sherlock_rest_service.settings"

[experimental]
  auto_rollback = true
  http2 = true
6612 2856
[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
5538 1348

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
